/*
 * AudioDub Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace MyDyb.Handler.Clients.MlService.Model
{
    /// <summary>
    /// GenerateAudioRequest
    /// </summary>
    [DataContract(Name = "GenerateAudioRequest")]
    public partial class GenerateAudioRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateAudioRequest" /> class.
        /// </summary>
        [JsonConstructor]
        protected GenerateAudioRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateAudioRequest" /> class.
        /// </summary>
        /// <param name="mediaId">mediaId (required).</param>
        /// <param name="trueDub">trueDub (required).</param>
        /// <param name="segments">segments (required).</param>
        public GenerateAudioRequest(string mediaId = default(string), bool trueDub = default(bool), List<Segment> segments = default(List<Segment>))
        {
            // to ensure "mediaId" is required (not null)
            if (mediaId == null)
            {
                throw new ArgumentNullException("mediaId is a required property for GenerateAudioRequest and cannot be null");
            }
            this.MediaId = mediaId;
            this.TrueDub = trueDub;
            // to ensure "segments" is required (not null)
            if (segments == null)
            {
                throw new ArgumentNullException("segments is a required property for GenerateAudioRequest and cannot be null");
            }
            this.Segments = segments;
        }

        /// <summary>
        /// Gets or Sets MediaId
        /// </summary>
        [DataMember(Name = "media_id", IsRequired = true, EmitDefaultValue = true)]
        public string MediaId { get; set; }

        /// <summary>
        /// Gets or Sets TrueDub
        /// </summary>
        [DataMember(Name = "true_dub", IsRequired = true, EmitDefaultValue = true)]
        public bool TrueDub { get; set; }

        /// <summary>
        /// Gets or Sets Segments
        /// </summary>
        [DataMember(Name = "segments", IsRequired = true, EmitDefaultValue = true)]
        public List<Segment> Segments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenerateAudioRequest {\n");
            sb.Append("  MediaId: ").Append(MediaId).Append("\n");
            sb.Append("  TrueDub: ").Append(TrueDub).Append("\n");
            sb.Append("  Segments: ").Append(Segments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
