/*
 * AudioDub Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace MyDyb.Handler.Clients.MlService.Model
{
    /// <summary>
    /// GenerateSegmentsResponse
    /// </summary>
    [DataContract(Name = "GenerateSegmentsResponse")]
    public partial class GenerateSegmentsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateSegmentsResponse" /> class.
        /// </summary>
        [JsonConstructor]
        protected GenerateSegmentsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateSegmentsResponse" /> class.
        /// </summary>
        /// <param name="segments">segments (required).</param>
        public GenerateSegmentsResponse(List<Segment> segments = default(List<Segment>))
        {
            // to ensure "segments" is required (not null)
            if (segments == null)
            {
                throw new ArgumentNullException("segments is a required property for GenerateSegmentsResponse and cannot be null");
            }
            this.Segments = segments;
        }

        /// <summary>
        /// Gets or Sets Segments
        /// </summary>
        [DataMember(Name = "segments", IsRequired = true, EmitDefaultValue = true)]
        public List<Segment> Segments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenerateSegmentsResponse {\n");
            sb.Append("  Segments: ").Append(Segments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
