/*
 * AudioDub Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace MyDyb.Handler.Clients.MlService.Model
{
    /// <summary>
    /// Segment
    /// </summary>
    [DataContract(Name = "Segment")]
    public partial class Segment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Segment" /> class.
        /// </summary>
        [JsonConstructor]
        protected Segment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Segment" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="startMs">startMs (required).</param>
        /// <param name="endMs">endMs (required).</param>
        /// <param name="speaker">speaker (required).</param>
        /// <param name="transcribe">transcribe (required).</param>
        /// <param name="translationRu">translationRu.</param>
        /// <param name="accentRu">accentRu.</param>
        /// <param name="audioMediaId">audioMediaId.</param>
        public Segment(string id = default(string), int startMs = default(int), int endMs = default(int), int speaker = default(int), string transcribe = default(string), string translationRu = default(string), string accentRu = default(string), string audioMediaId = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Segment and cannot be null");
            }
            this.Id = id;
            this.StartMs = startMs;
            this.EndMs = endMs;
            this.Speaker = speaker;
            // to ensure "transcribe" is required (not null)
            if (transcribe == null)
            {
                throw new ArgumentNullException("transcribe is a required property for Segment and cannot be null");
            }
            this.Transcribe = transcribe;
            this.TranslationRu = translationRu;
            this.AccentRu = accentRu;
            this.AudioMediaId = audioMediaId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets StartMs
        /// </summary>
        [DataMember(Name = "start_ms", IsRequired = true, EmitDefaultValue = true)]
        public int StartMs { get; set; }

        /// <summary>
        /// Gets or Sets EndMs
        /// </summary>
        [DataMember(Name = "end_ms", IsRequired = true, EmitDefaultValue = true)]
        public int EndMs { get; set; }

        /// <summary>
        /// Gets or Sets Speaker
        /// </summary>
        [DataMember(Name = "speaker", IsRequired = true, EmitDefaultValue = true)]
        public int Speaker { get; set; }

        /// <summary>
        /// Gets or Sets Transcribe
        /// </summary>
        [DataMember(Name = "transcribe", IsRequired = true, EmitDefaultValue = true)]
        public string Transcribe { get; set; }

        /// <summary>
        /// Gets or Sets TranslationRu
        /// </summary>
        [DataMember(Name = "translation_ru", EmitDefaultValue = true)]
        public string TranslationRu { get; set; }

        /// <summary>
        /// Gets or Sets AccentRu
        /// </summary>
        [DataMember(Name = "accent_ru", EmitDefaultValue = true)]
        public string AccentRu { get; set; }

        /// <summary>
        /// Gets or Sets AudioMediaId
        /// </summary>
        [DataMember(Name = "audio_media_id", EmitDefaultValue = true)]
        public string AudioMediaId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Segment {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StartMs: ").Append(StartMs).Append("\n");
            sb.Append("  EndMs: ").Append(EndMs).Append("\n");
            sb.Append("  Speaker: ").Append(Speaker).Append("\n");
            sb.Append("  Transcribe: ").Append(Transcribe).Append("\n");
            sb.Append("  TranslationRu: ").Append(TranslationRu).Append("\n");
            sb.Append("  AccentRu: ").Append(AccentRu).Append("\n");
            sb.Append("  AudioMediaId: ").Append(AudioMediaId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
