/*
 * AudioDub Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace MyDyb.Handler.Clients.MlService.Model
{
    /// <summary>
    /// SynthesizeSegmentRequest
    /// </summary>
    [DataContract(Name = "SynthesizeSegmentRequest")]
    public partial class SynthesizeSegmentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SynthesizeSegmentRequest" /> class.
        /// </summary>
        [JsonConstructor]
        protected SynthesizeSegmentRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SynthesizeSegmentRequest" /> class.
        /// </summary>
        /// <param name="mediaId">mediaId (required).</param>
        /// <param name="segment">segment (required).</param>
        public SynthesizeSegmentRequest(string mediaId = default(string), Segment segment = default(Segment))
        {
            // to ensure "mediaId" is required (not null)
            if (mediaId == null)
            {
                throw new ArgumentNullException("mediaId is a required property for SynthesizeSegmentRequest and cannot be null");
            }
            this.MediaId = mediaId;
            // to ensure "segment" is required (not null)
            if (segment == null)
            {
                throw new ArgumentNullException("segment is a required property for SynthesizeSegmentRequest and cannot be null");
            }
            this.Segment = segment;
        }

        /// <summary>
        /// Gets or Sets MediaId
        /// </summary>
        [DataMember(Name = "media_id", IsRequired = true, EmitDefaultValue = true)]
        public string MediaId { get; set; }

        /// <summary>
        /// Gets or Sets Segment
        /// </summary>
        [DataMember(Name = "segment", IsRequired = true, EmitDefaultValue = true)]
        public Segment Segment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SynthesizeSegmentRequest {\n");
            sb.Append("  MediaId: ").Append(MediaId).Append("\n");
            sb.Append("  Segment: ").Append(Segment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
