/*
 * AudioDub Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using MyDyb.Handler.Clients.MlService.Client;
using MyDyb.Handler.Clients.MlService.Model;

namespace MyDyb.Handler.Clients.MlService.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISegmentsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Segment
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SynthesizeSegmentResponse</returns>
        SynthesizeSegmentResponse CreateSegmentApiSegmentsSynthesizePost(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0);

        /// <summary>
        /// Create Segment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SynthesizeSegmentResponse</returns>
        ApiResponse<SynthesizeSegmentResponse> CreateSegmentApiSegmentsSynthesizePostWithHttpInfo(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0);
        /// <summary>
        /// Create Segments
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GenerateSegmentsResponse</returns>
        GenerateSegmentsResponse CreateSegmentsApiSegmentsGeneratePost(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0);

        /// <summary>
        /// Create Segments
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GenerateSegmentsResponse</returns>
        ApiResponse<GenerateSegmentsResponse> CreateSegmentsApiSegmentsGeneratePostWithHttpInfo(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISegmentsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Segment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SynthesizeSegmentResponse</returns>
        System.Threading.Tasks.Task<SynthesizeSegmentResponse> CreateSegmentApiSegmentsSynthesizePostAsync(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create Segment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SynthesizeSegmentResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SynthesizeSegmentResponse>> CreateSegmentApiSegmentsSynthesizePostWithHttpInfoAsync(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Create Segments
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GenerateSegmentsResponse</returns>
        System.Threading.Tasks.Task<GenerateSegmentsResponse> CreateSegmentsApiSegmentsGeneratePostAsync(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create Segments
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GenerateSegmentsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenerateSegmentsResponse>> CreateSegmentsApiSegmentsGeneratePostWithHttpInfoAsync(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISegmentsApi : ISegmentsApiSync, ISegmentsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SegmentsApi : ISegmentsApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SegmentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SegmentsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SegmentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SegmentsApi(string basePath)
        {
            this.Configuration = MlService.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration { BasePath = basePath }
            );
            this.Client = new ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MlService.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SegmentsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SegmentsApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MlService.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MlService.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SegmentsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SegmentsApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MlService.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Segment 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SynthesizeSegmentResponse</returns>
        public SynthesizeSegmentResponse CreateSegmentApiSegmentsSynthesizePost(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0)
        {
            ApiResponse<SynthesizeSegmentResponse> localVarResponse = CreateSegmentApiSegmentsSynthesizePostWithHttpInfo(synthesizeSegmentRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Segment 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SynthesizeSegmentResponse</returns>
        public ApiResponse<SynthesizeSegmentResponse> CreateSegmentApiSegmentsSynthesizePostWithHttpInfo(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0)
        {
            // verify the required parameter 'synthesizeSegmentRequest' is set
            if (synthesizeSegmentRequest == null)
            {
                throw new ApiException(400, "Missing required parameter 'synthesizeSegmentRequest' when calling SegmentsApi->CreateSegmentApiSegmentsSynthesizePost");
            }

            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = synthesizeSegmentRequest;

            localVarRequestOptions.Operation = "SegmentsApi.CreateSegmentApiSegmentsSynthesizePost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<SynthesizeSegmentResponse>("/api/segments/synthesize", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateSegmentApiSegmentsSynthesizePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Segment 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SynthesizeSegmentResponse</returns>
        public async System.Threading.Tasks.Task<SynthesizeSegmentResponse> CreateSegmentApiSegmentsSynthesizePostAsync(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ApiResponse<SynthesizeSegmentResponse> localVarResponse = await CreateSegmentApiSegmentsSynthesizePostWithHttpInfoAsync(synthesizeSegmentRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Segment 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="synthesizeSegmentRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SynthesizeSegmentResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SynthesizeSegmentResponse>> CreateSegmentApiSegmentsSynthesizePostWithHttpInfoAsync(SynthesizeSegmentRequest synthesizeSegmentRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'synthesizeSegmentRequest' is set
            if (synthesizeSegmentRequest == null)
            {
                throw new ApiException(400, "Missing required parameter 'synthesizeSegmentRequest' when calling SegmentsApi->CreateSegmentApiSegmentsSynthesizePost");
            }


            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = synthesizeSegmentRequest;

            localVarRequestOptions.Operation = "SegmentsApi.CreateSegmentApiSegmentsSynthesizePost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SynthesizeSegmentResponse>("/api/segments/synthesize", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateSegmentApiSegmentsSynthesizePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Segments 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GenerateSegmentsResponse</returns>
        public GenerateSegmentsResponse CreateSegmentsApiSegmentsGeneratePost(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0)
        {
            ApiResponse<GenerateSegmentsResponse> localVarResponse = CreateSegmentsApiSegmentsGeneratePostWithHttpInfo(generateSegmentsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Segments 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GenerateSegmentsResponse</returns>
        public ApiResponse<GenerateSegmentsResponse> CreateSegmentsApiSegmentsGeneratePostWithHttpInfo(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0)
        {
            // verify the required parameter 'generateSegmentsRequest' is set
            if (generateSegmentsRequest == null)
            {
                throw new ApiException(400, "Missing required parameter 'generateSegmentsRequest' when calling SegmentsApi->CreateSegmentsApiSegmentsGeneratePost");
            }

            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = generateSegmentsRequest;

            localVarRequestOptions.Operation = "SegmentsApi.CreateSegmentsApiSegmentsGeneratePost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<GenerateSegmentsResponse>("/api/segments/generate", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateSegmentsApiSegmentsGeneratePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Segments 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GenerateSegmentsResponse</returns>
        public async System.Threading.Tasks.Task<GenerateSegmentsResponse> CreateSegmentsApiSegmentsGeneratePostAsync(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            ApiResponse<GenerateSegmentsResponse> localVarResponse = await CreateSegmentsApiSegmentsGeneratePostWithHttpInfoAsync(generateSegmentsRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Segments 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="generateSegmentsRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GenerateSegmentsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenerateSegmentsResponse>> CreateSegmentsApiSegmentsGeneratePostWithHttpInfoAsync(GenerateSegmentsRequest generateSegmentsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'generateSegmentsRequest' is set
            if (generateSegmentsRequest == null)
            {
                throw new ApiException(400, "Missing required parameter 'generateSegmentsRequest' when calling SegmentsApi->CreateSegmentsApiSegmentsGeneratePost");
            }


            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = generateSegmentsRequest;

            localVarRequestOptions.Operation = "SegmentsApi.CreateSegmentsApiSegmentsGeneratePost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<GenerateSegmentsResponse>("/api/segments/generate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateSegmentsApiSegmentsGeneratePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
